version: '3'
services:
  server:
    build: ./server
    ports:
      - 3000:3000
    volumes:
      - ./server:/app
      - ./scenes:/app/scenes
    command: npm run dev
    # command: tail -F anything.js
    networks:
      - robot_network
    depends_on:
      - flask-server

  flask-server:
    build: ./flask-server
    container_name: flask_app
    volumes:
      - ./flask-server:/app
    restart: always
    command: python3 app.py
    # command: tail -F anything.js
    ports:
      - 5000:5000 
    networks:
      - robot_network 

  unpack:
    build: ./scenes
    volumes:
      - ./scenes:/app

networks:
  robot_network: